SEED_MECHANICS = [
    {
        "name": "Delhi Motor Works",
        "rating": 4.7,  
        "latitude": 28.6284,
        "longitude": 77.2188,
        "location_name": "Connaught Place",
        "address": "G-14, Outer Circle, Connaught Place, New Delhi, Delhi 110001",
        "available_services": ["AC Repair", "Suspension Tuning", "Wheel Alignment"],
        "working_hours": "Mon-Sun: 10:00 AM - 7:30 PM",
        "phone_number": "+91-9812345678",
        "is_open": True,
    },
    {
        "name": "Noida Auto Tech",
        "rating": 4.2,
        "latitude": 28.5708,
        "longitude": 77.3259,
        "location_name": "Sector 18",
        "address": "Block E-21, Pocket 2, Sector 18, Noida, Uttar Pradesh 201301",
        "available_services": ["Oil Change", "Battery Replacement", "Brake Repair"],
        "working_hours": "Tue-Sun: 9:30 AM - 8:30 PM",
        "phone_number": "+91-9999888777",
        "is_open": True,
    },
    {
        "name": "Speedy Car Care",
        "rating": 4.4,
        "latitude": 28.4947,
        "longitude": 77.0894,
        "location_name": "DLF Phase 3",
        "address": "Plot 45, Nathupur Road, DLF Phase 3, Gurugram, Haryana 122002",
        "available_services": ["Car Washing", "Denting & Painting", "Engine Diagnostics"],
        "working_hours": "Mon-Sat: 8:00 AM - 7:00 PM",
        "phone_number": "+91-9560123456",
        "is_open": True,
    },
    {
        "name": "Capital Garage & Spares",
        "rating": 4.6,
        "latitude": 28.5454,
        "longitude": 77.2628,
        "location_name": "Nehru Place",
        "address": "Shop 4, Nehru Place Market, New Delhi, Delhi 110019",
        "available_services": ["Clutch Overhaul", "Gearbox Repair", "Brake Repair"],
        "working_hours": "Mon-Sat: 10:00 AM - 8:00 PM",
        "phone_number": "+91-9871122334",
        "is_open": False,
    },
    {
        "name": "Cyber City Pitstop",
        "rating": 4.8,
        "latitude": 28.4953,
        "longitude": 77.0924,
        "location_name": "DLF Cyber City",
        "address": "Building 10, Tower B Basement, Cyber City, Gurugram, Haryana 122002",
        "available_services": ["Oil Change", "Tyre Replacement", "Windshield Repair"],
        "working_hours": "Mon-Fri: 8:00 AM - 10:00 PM",
        "phone_number": "+91-9111222333",
        "is_open": True,
    },
    {
        "name": "Express Auto Station",
        "rating": 3.9,
        "latitude": 28.5823,
        "longitude": 77.3125,
        "location_name": "Sector 62",
        "address": "C-56/3, Institutional Area, Sector 62, Noida, Uttar Pradesh 201309",
        "available_services": ["Electrical Fault Repair", "Engine Diagnostics", "Battery Replacement"],
        "working_hours": "Mon-Sat: 9:00 AM - 6:30 PM",
        "phone_number": "+91-8882233445",
        "is_open": True,
    },
    {
        "name": "Royal Wheels Automobile",
        "rating": 4.3,
        "latitude": 28.6365,
        "longitude": 77.1006,
        "location_name": "Rajouri Garden",
        "address": "J-12, Main Ring Road, Rajouri Garden, New Delhi, Delhi 110027",
        "available_services": ["Car Detailing", "Ceramic Coating", "Oil Change"],
        "working_hours": "Wed-Mon: 10:00 AM - 8:00 PM",
        "phone_number": "+91-9811009988",
        "is_open": True,
    },
    {
        "name": "Elite Motors Gurugram",
        "rating": 4.1,
        "latitude": 28.4194,
        "longitude": 77.0391,
        "location_name": "Sohna Road",
        "address": "Ground Floor, Sapphire Mall, Sector 49, Sohna Road, Gurugram, Haryana 122018",
        "available_services": ["Brake Repair", "Suspension Tuning", "AC Repair"],
        "working_hours": "Mon-Sun: 9:00 AM - 9:00 PM",
        "phone_number": "+91-7042345678",
        "is_open": True,
    },
    {
        "name": "Apex Car Mechanics",
        "rating": 4.5,
        "latitude": 28.5355,
        "longitude": 77.1959,
        "location_name": "Safdarjung Enclave",
        "address": "B-6/10, Commercial Complex, Safdarjung Enclave, New Delhi, Delhi 110029",
        "available_services": ["Engine Diagnostics", "Transmission Fluid Change", "Wheel Alignment"],
        "working_hours": "Mon-Sat: 9:30 AM - 7:30 PM",
        "phone_number": "+91-9958123456",
        "is_open": True,
    },
    {
        "name": "Metro Auto Electricals",
        "rating": 4.0,
        "latitude": 28.6145,
        "longitude": 77.3789,
        "location_name": "Sector 50",
        "address": "Shop 18, Central Market, Sector 50, Noida, Uttar Pradesh 201301",
        "available_services": ["Battery Replacement", "Headlight Restoration", "AC Repair"],
        "working_hours": "Tue-Sun: 10:00 AM - 8:00 PM",
        "phone_number": "+91-9650987654",
        "is_open": False,
    }
]
